applications:
  kafka-k8s:
    channel: edge
    charm: kafka-k8s
    constraints: arch=amd64
    revision: 12
    scale: 1
  tls-certificates-operator:
    channel: edge
    charm: tls-certificates-operator
    constraints: arch=amd64
    options:
      ca-common-name: canonical
      generate-self-signed-certificates: true
    revision: 11
    scale: 1
  zookeeper-k8s:
    channel: edge
    charm: zookeeper-k8s
    constraints: arch=amd64
    revision: 15
    scale: 3
bundle: kubernetes
relations:
- - zookeeper-k8s:certificates
  - tls-certificates-operator:certificates
- - kafka-k8s:zookeeper
  - zookeeper-k8s:zookeeper
- - kafka-k8s:certificates
  - tls-certificates-operator:certificates
